//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benutomo.AutomaticDisposeImpl.SourceGenerator {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Benutomo.AutomaticDisposeImpl.SourceGenerator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   A definition of the type to which the AutomaticDisposeImpl attribute is attached must be partial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG0001_Message {
            get {
                return ResourceManager.GetString("SG0001_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A type to which the AutomaticDisposeImpl attribute is attached must have the partial keyword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG0001_Title {
            get {
                return ResourceManager.GetString("SG0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A type with the AutomaticDisposeImpl attribute must implement one or both of IDisposable and IAsyncDisposable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG0002_Message {
            get {
                return ResourceManager.GetString("SG0002_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A type to which the AutomaticDisposeImpl attribute is attached requires an IDisposable or IAsyncDisposable interface に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG0002_Title {
            get {
                return ResourceManager.GetString("SG0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Since {0} implements IAsyncDisposable, asynchronous destruction by the DisposeAsync() method is possible, but since {1} does not implement IAsyncDisposable, it is always destroyed synchronously by Dispose(). Please add IAsyncDisposable to the implementation interface of {1} to support asynchronous destruction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG0003_Message {
            get {
                return ResourceManager.GetString("SG0003_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The IAsyncDisposable interface is required to use the asynchronous destruction methods of the members に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG0003_Title {
            get {
                return ResourceManager.GetString("SG0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} implements IAsyncDisposable but does not implement IDisposable. Since {1} implements only IDisposable, this member is not subject to automatic destruction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG0004_Message {
            get {
                return ResourceManager.GetString("SG0004_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Members that support only asynchronous destruction are not auto-destructed by classes that implement only IDiposable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG0004_Title {
            get {
                return ResourceManager.GetString("SG0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic implementation of Dispose for {0} failed due to an unknown internal error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG9998_Message {
            get {
                return ResourceManager.GetString("SG9998_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failure of source generation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG9998_Title {
            get {
                return ResourceManager.GetString("SG9998_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AutomaticDisposeGenerator has stopped due to an unknown internal error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG9999_Message {
            get {
                return ResourceManager.GetString("SG9999_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abnormal termination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SG9999_Title {
            get {
                return ResourceManager.GetString("SG9999_Title", resourceCulture);
            }
        }
    }
}
